// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: users/v1/authenticate_user.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserAuthenticateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAuthenticateRequest) Reset() {
	*x = UserAuthenticateRequest{}
	mi := &file_users_v1_authenticate_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAuthenticateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAuthenticateRequest) ProtoMessage() {}

func (x *UserAuthenticateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_v1_authenticate_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAuthenticateRequest.ProtoReflect.Descriptor instead.
func (*UserAuthenticateRequest) Descriptor() ([]byte, []int) {
	return file_users_v1_authenticate_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserAuthenticateRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserAuthenticateRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UserAuthenticateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAuthenticateResponse) Reset() {
	*x = UserAuthenticateResponse{}
	mi := &file_users_v1_authenticate_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAuthenticateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAuthenticateResponse) ProtoMessage() {}

func (x *UserAuthenticateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_v1_authenticate_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAuthenticateResponse.ProtoReflect.Descriptor instead.
func (*UserAuthenticateResponse) Descriptor() ([]byte, []int) {
	return file_users_v1_authenticate_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserAuthenticateResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_users_v1_authenticate_user_proto protoreflect.FileDescriptor

const file_users_v1_authenticate_user_proto_rawDesc = "" +
	"\n" +
	" users/v1/authenticate_user.proto\x12\busers.v1\"K\n" +
	"\x17UserAuthenticateRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"*\n" +
	"\x18UserAuthenticateResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02idB\"Z users_service/pkg/proto/users/v1b\x06proto3"

var (
	file_users_v1_authenticate_user_proto_rawDescOnce sync.Once
	file_users_v1_authenticate_user_proto_rawDescData []byte
)

func file_users_v1_authenticate_user_proto_rawDescGZIP() []byte {
	file_users_v1_authenticate_user_proto_rawDescOnce.Do(func() {
		file_users_v1_authenticate_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_users_v1_authenticate_user_proto_rawDesc), len(file_users_v1_authenticate_user_proto_rawDesc)))
	})
	return file_users_v1_authenticate_user_proto_rawDescData
}

var file_users_v1_authenticate_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_users_v1_authenticate_user_proto_goTypes = []any{
	(*UserAuthenticateRequest)(nil),  // 0: users.v1.UserAuthenticateRequest
	(*UserAuthenticateResponse)(nil), // 1: users.v1.UserAuthenticateResponse
}
var file_users_v1_authenticate_user_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_users_v1_authenticate_user_proto_init() }
func file_users_v1_authenticate_user_proto_init() {
	if File_users_v1_authenticate_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_users_v1_authenticate_user_proto_rawDesc), len(file_users_v1_authenticate_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_users_v1_authenticate_user_proto_goTypes,
		DependencyIndexes: file_users_v1_authenticate_user_proto_depIdxs,
		MessageInfos:      file_users_v1_authenticate_user_proto_msgTypes,
	}.Build()
	File_users_v1_authenticate_user_proto = out.File
	file_users_v1_authenticate_user_proto_goTypes = nil
	file_users_v1_authenticate_user_proto_depIdxs = nil
}
