// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: users/v1/users_service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UsersServiceV1_CreateUser_FullMethodName       = "/users.v1.UsersServiceV1/CreateUser"
	UsersServiceV1_AuthenticateUser_FullMethodName = "/users.v1.UsersServiceV1/AuthenticateUser"
)

// UsersServiceV1Client is the client API for UsersServiceV1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UsersServiceV1Client interface {
	CreateUser(ctx context.Context, in *UserRegisterRequest, opts ...grpc.CallOption) (*UserRegisterResponse, error)
	AuthenticateUser(ctx context.Context, in *UserAuthenticateRequest, opts ...grpc.CallOption) (*UserAuthenticateResponse, error)
}

type usersServiceV1Client struct {
	cc grpc.ClientConnInterface
}

func NewUsersServiceV1Client(cc grpc.ClientConnInterface) UsersServiceV1Client {
	return &usersServiceV1Client{cc}
}

func (c *usersServiceV1Client) CreateUser(ctx context.Context, in *UserRegisterRequest, opts ...grpc.CallOption) (*UserRegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserRegisterResponse)
	err := c.cc.Invoke(ctx, UsersServiceV1_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceV1Client) AuthenticateUser(ctx context.Context, in *UserAuthenticateRequest, opts ...grpc.CallOption) (*UserAuthenticateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserAuthenticateResponse)
	err := c.cc.Invoke(ctx, UsersServiceV1_AuthenticateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsersServiceV1Server is the server API for UsersServiceV1 service.
// All implementations must embed UnimplementedUsersServiceV1Server
// for forward compatibility.
type UsersServiceV1Server interface {
	CreateUser(context.Context, *UserRegisterRequest) (*UserRegisterResponse, error)
	AuthenticateUser(context.Context, *UserAuthenticateRequest) (*UserAuthenticateResponse, error)
	mustEmbedUnimplementedUsersServiceV1Server()
}

// UnimplementedUsersServiceV1Server must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUsersServiceV1Server struct{}

func (UnimplementedUsersServiceV1Server) CreateUser(context.Context, *UserRegisterRequest) (*UserRegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedUsersServiceV1Server) AuthenticateUser(context.Context, *UserAuthenticateRequest) (*UserAuthenticateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthenticateUser not implemented")
}
func (UnimplementedUsersServiceV1Server) mustEmbedUnimplementedUsersServiceV1Server() {}
func (UnimplementedUsersServiceV1Server) testEmbeddedByValue()                        {}

// UnsafeUsersServiceV1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UsersServiceV1Server will
// result in compilation errors.
type UnsafeUsersServiceV1Server interface {
	mustEmbedUnimplementedUsersServiceV1Server()
}

func RegisterUsersServiceV1Server(s grpc.ServiceRegistrar, srv UsersServiceV1Server) {
	// If the following call pancis, it indicates UnimplementedUsersServiceV1Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UsersServiceV1_ServiceDesc, srv)
}

func _UsersServiceV1_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceV1Server).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsersServiceV1_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceV1Server).CreateUser(ctx, req.(*UserRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersServiceV1_AuthenticateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserAuthenticateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceV1Server).AuthenticateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsersServiceV1_AuthenticateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceV1Server).AuthenticateUser(ctx, req.(*UserAuthenticateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UsersServiceV1_ServiceDesc is the grpc.ServiceDesc for UsersServiceV1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UsersServiceV1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "users.v1.UsersServiceV1",
	HandlerType: (*UsersServiceV1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UsersServiceV1_CreateUser_Handler,
		},
		{
			MethodName: "AuthenticateUser",
			Handler:    _UsersServiceV1_AuthenticateUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "users/v1/users_service.proto",
}
