// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: users/v1/users_service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_users_v1_users_service_proto protoreflect.FileDescriptor

const file_users_v1_users_service_proto_rawDesc = "" +
	"\n" +
	"\x1cusers/v1/users_service.proto\x12\busers.v1\x1a\x1ausers/v1/create_user.proto\x1a users/v1/authenticate_user.proto2\xb8\x01\n" +
	"\x0eUsersServiceV1\x12K\n" +
	"\n" +
	"CreateUser\x12\x1d.users.v1.UserRegisterRequest\x1a\x1e.users.v1.UserRegisterResponse\x12Y\n" +
	"\x10AuthenticateUser\x12!.users.v1.UserAuthenticateRequest\x1a\".users.v1.UserAuthenticateResponseB\"Z users_service/pkg/proto/users/v1b\x06proto3"

var file_users_v1_users_service_proto_goTypes = []any{
	(*UserRegisterRequest)(nil),      // 0: users.v1.UserRegisterRequest
	(*UserAuthenticateRequest)(nil),  // 1: users.v1.UserAuthenticateRequest
	(*UserRegisterResponse)(nil),     // 2: users.v1.UserRegisterResponse
	(*UserAuthenticateResponse)(nil), // 3: users.v1.UserAuthenticateResponse
}
var file_users_v1_users_service_proto_depIdxs = []int32{
	0, // 0: users.v1.UsersServiceV1.CreateUser:input_type -> users.v1.UserRegisterRequest
	1, // 1: users.v1.UsersServiceV1.AuthenticateUser:input_type -> users.v1.UserAuthenticateRequest
	2, // 2: users.v1.UsersServiceV1.CreateUser:output_type -> users.v1.UserRegisterResponse
	3, // 3: users.v1.UsersServiceV1.AuthenticateUser:output_type -> users.v1.UserAuthenticateResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_users_v1_users_service_proto_init() }
func file_users_v1_users_service_proto_init() {
	if File_users_v1_users_service_proto != nil {
		return
	}
	file_users_v1_create_user_proto_init()
	file_users_v1_authenticate_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_users_v1_users_service_proto_rawDesc), len(file_users_v1_users_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_users_v1_users_service_proto_goTypes,
		DependencyIndexes: file_users_v1_users_service_proto_depIdxs,
	}.Build()
	File_users_v1_users_service_proto = out.File
	file_users_v1_users_service_proto_goTypes = nil
	file_users_v1_users_service_proto_depIdxs = nil
}
